name: Auto Update M3U8

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Fetch M3U8 Link
      run: |
        # এখন টিভির লাইভ ভিডিও আইডি (PRvnQNOaTFg) ব্যবহার করে সরাসরি m3u8 লিংক জেনারেট করা
        VIDEO_ID="PRvnQNOaTFg"
        M3U8_URL="https://youtube.com/api/manifest/hls_variant/id/${VIDEO_ID}/source/yt_live_broadcast/file/index.m3u8"
        
        # m3u ফাইল তৈরি করা
        echo "#EXTM3U" > ekhon_tv.m3u
        echo '#EXTINF:-1 tvg-id="EkhonTV" tvg-name="Ekhon TV" tvg-logo="https://raw.githubusercontent.com/arshatb/EkhonTV-m3u8/main/logo.png" group-title="News",Ekhon TV' >> ekhon_tv.m3u
        echo "$M3U8_URL" >> ekhon_tv.m3u
        
        echo "Link successfully generated!"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ekhon_tv.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated Live Link" && git push)
